
id = "Webphishing"
name = "Webphishing"
description = "Phish tribute mod for Webfishing."
version = "1.0.0"
homepage = "https://github.com/NotNite/WebfishingSampleMod"
author = "Taxman"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./WebfishingSampleMod/WebfishingSampleMod.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
